<a href="https://colab.research.google.com/github/suhaassanga/2216114_AIML_BootCamp/blob/Suhaas-Sanga/Text_Navie_23_06_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [26]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/drive/MyDrive/SMSSpamCollection', sep='\t',header=None,names=['label','message'])

In [4]:
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.shape

(5572, 2)

In [6]:
#data preprocessing
df['label']=df.label.map({'ham':0,'spam':1})

In [7]:
df.head()

label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [8]:
#Bag of words (Bow)-sklearn
documents =['hello,how are you?',
            'Win money win from home',
            'Call me now',
            'Hello Call hello you tomorrow?']
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
cv.fit(documents)

CountVectorizer()

In [9]:
n=cv.get_feature_names()
print(n)

['are', 'call', 'from', 'hello', 'home', 'how', 'me', 'money', 'now', 'tomorrow', 'win', 'you']


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [10]:
doc_array=cv.transform(documents).toarray()
print(doc_array)

[[1 0 0 1 0 1 0 0 0 0 0 1]
 [0 0 1 0 1 0 0 1 0 0 2 0]
 [0 1 0 0 0 0 1 0 1 0 0 0]
 [0 1 0 2 0 0 0 0 0 1 0 1]]


In [11]:
#converting this array into dataframe 
freq_table=pd.DataFrame(data=doc_array,columns=n)

In [12]:
print(freq_table)

   are  call  from  hello  home  how  me  money  now  tomorrow  win  you
0    1     0     0      1     0    1   0      0    0         0    0    1
1    0     0     1      0     1    0   0      1    0         0    2    0
2    0     1     0      0     0    0   1      0    1         0    0    0
3    0     1     0      2     0    0   0      0    0         1    0    1


In [13]:
df.head()

label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [14]:
#load the data
x=df.iloc[:,-1:]#independent -message column
y=df.iloc[:,:-1]#dependent -label column
#method 2
'''import numpy as np
x=np.array(df['message'])
y=np.array(df['label'])'''

"import numpy as np\nx=np.array(df['message'])\ny=np.array(df['label'])"

In [15]:
print(x)

                                                message
0     Go until jurong point, crazy.. Available only ...
1                         Ok lar... Joking wif u oni...
2     Free entry in 2 a wkly comp to win FA Cup fina...
3     U dun say so early hor... U c already then say...
4     Nah I don't think he goes to usf, he lives aro...
...                                                 ...
5567  This is the 2nd time we have tried 2 contact u...
5568               Will ü b going to esplanade fr home?
5569  Pity, * was in mood for that. So...any other s...
5570  The guy did some bitching but I acted like i'd...
5571                         Rofl. Its true to its name

[5572 rows x 1 columns]


In [16]:
print(y)

      label
0         0
1         0
2         1
3         0
4         0
...     ...
5567      1
5568      0
5569      0
5570      0
5571      0

[5572 rows x 1 columns]


In [17]:
#split the data in to training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1,shuffle=True)

In [18]:
x_train

message
1642  Hi , where are you? We're at  and they're not ...
2899        If you r @ home then come down within 5 min
480   When're you guys getting back? G said you were...
3485  Tell my  bad character which u Dnt lik in me. ...
157                         I'm leaving my house now...
...                                                 ...
905   We're all getting worried over here, derek and...
5192  Oh oh... Den muz change plan liao... Go back h...
3980  CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C...
235   Text & meet someone sexy today. U can find a d...
5157                            K k:) sms chat with me.

[4457 rows x 1 columns]

In [19]:
x_test

message
1078                       Yep, by the pretty sculpture
4028      Yes, princess. Are you going to make me moan?
958                          Welp apparently he retired
4642                                            Havent.
4674  I forgot 2 ask ü all smth.. There's a card on ...
...                                                 ...
324   That would be great. We'll be at the Guild. Co...
1163  Free entry in 2 a wkly comp to win FA Cup fina...
86    For real when u getting on yo? I only need 2 m...
4214                   I attended but nothing is there.
90    Yeah do! Don‘t stand to close tho- you‘ll catc...

[1115 rows x 1 columns]

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
#transform the training data into freq vectors and return the matrix
training_data=cv.fit_transform(x_train.values.flatten())

#transform the testing data into freq vectors and return the matrix
testing_data=cv.transform(x_test.values.flatten())

In [21]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()

In [22]:
model.fit(training_data,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB()

In [24]:
y_test=y_test.values.flatten()
print(y_test)

[0 0 0 ... 0 0 0]


In [27]:
y_pred=model.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [28]:
print("Predicted value for training data:",model.score(training_data,y_train))
print("Training accuracy:",model.score(training_data,y_train)*100)

Predicted value for training data: 0.9923715503702042
Training accuracy: 99.23715503702041


In [29]:
print("Predicted value for testing data:",model.score(testing_data,y_test))
print("Testing accuracy:",model.score(testing_data,y_test)*100)

Predicted value for testing data: 0.9901345291479821
Testing accuracy: 99.01345291479821


In [30]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)*100

[[965   3]
 [  8 139]]


99.01345291479821

In [31]:
from sklearn.tree import DecisionTreeClassifier
modeldt=DecisionTreeClassifier()

In [32]:
modeldt.fit(training_data,y_train)

DecisionTreeClassifier()

In [33]:
y_pred=modeldt.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [34]:
print("Predicted value for training data:",modeldt.score(training_data,y_train))
print("Training accuracy:",modeldt.score(training_data,y_train)*100)

Predicted value for training data: 1.0
Training accuracy: 100.0


In [35]:
print("Predicted value for testing data:",modeldt.score(testing_data,y_test))
print("Testing accuracy:",modeldt.score(testing_data,y_test)*100)

Predicted value for testing data: 0.9730941704035875
Testing accuracy: 97.30941704035875


In [36]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)*100

[[952  16]
 [ 14 133]]


97.30941704035875

In [37]:
from sklearn.svm import SVC
modelsvc=SVC()

In [38]:
modelsvc.fit(training_data,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [39]:
y_pred=modelsvc.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [40]:
print("Predicted value for training data:",modelsvc.score(training_data,y_train))
print("Training accuracy:",modelsvc.score(training_data,y_train)*100)

Predicted value for training data: 0.9950639443571909
Training accuracy: 99.50639443571909


In [41]:
print("Predicted value for testing data:",modelsvc.score(testing_data,y_test))
print("Testing accuracy:",modelsvc.score(testing_data,y_test)*100)

Predicted value for testing data: 0.9874439461883409
Testing accuracy: 98.7443946188341


In [42]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)*100

[[967   1]
 [ 13 134]]


98.7443946188341

In [43]:
from sklearn.ensemble import RandomForestClassifier
modelrf=RandomForestClassifier()

In [44]:
modelrf.fit(training_data,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier()

In [45]:
y_pred=modelrf.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [46]:
print("Predicted value for training data:",modelrf.score(training_data,y_train))
print("Training accuracy:",modelrf.score(training_data,y_train)*100)

Predicted value for training data: 1.0
Training accuracy: 100.0


In [47]:
print("Predicted value for testing data:",modelrf.score(testing_data,y_test))
print("Testing accuracy:",modelrf.score(testing_data,y_test)*100)

Predicted value for testing data: 0.9802690582959641
Testing accuracy: 98.02690582959642


In [48]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)*100

[[968   0]
 [ 22 125]]


98.02690582959642